Implement List Section in the ASR Pass
lcompilers/lpython pull request #1184
Opened 2022-10-06 10:10 UTC by Thirumalai-Shaktivel

Fixes: #1177

2022-10-06 10:11 UTC, Thirumalai-Shaktivel commented on integration_tests/test_list_10.py
> +
@czgdp1807, do you suggest any other tests?

2022-10-09 05:59 UTC, czgdp1807 requested changes
Please rename,

1. `class ListASRPass` -> `class ListExprReplacer`
2. `class ListConcatVisitor` -> `class ListExprVisitor`
3. `pass_list_concat` -> `pass_list_expr`

The implementation and the tests look fine to me.

2022-10-09 07:26 UTC, Thirumalai-Shaktivel commented
@czgdp1807, I applied your suggestions and provided support for list section step `x[::2]`. If everything looks good I will start polishing the commit

2022-10-09 12:48 UTC, czgdp1807 approved these changes

2022-10-10 05:35 UTC, Thirumalai-Shaktivel commented
Thanks for the review!

2022-10-10 05:36 UTC, czgdp1807 commented
Please wait for https://github.com/lfortran/lfortran/pull/875 to be merged.

2022-10-10 05:37 UTC, Thirumalai-Shaktivel commented
Yup, I will polish the commit and keep it.

2022-10-11 04:24 UTC, merged