Fixes handling of while loop during pass
lcompilers/lpython pull request #1570
Opened 2023-03-09 13:00 UTC by anutosh491

Fixes #1569 
```
def f():                                            
    j :i32 = 0
    while True:
        j = j + 1
        print(j)
        if(j>4):
            break
    print("out of outer loop")
f()
```
On Branch
```
(lp) C:\Users\kunni\lpython>lpython try.py
1
2
3
4
5
out of outer loop
```
On Master
```
(lp) C:\Users\kunni\lpython>src\bin\lpython try.py
1
2
3
4
5
5
5
out of outer loop
```

2023-03-09 17:21 UTC, czgdp1807 requested changes

2023-03-09 17:21 UTC, czgdp1807 commented on integration_tests/loop_05.py
> +        if(j>4):
```suggestion
        if j > 4:
```

2023-03-09 17:21 UTC, czgdp1807 commented on integration_tests/loop_05.py
> +    print("out of outer loop")
```suggestion
    print("out of outer loop")
    assert j == 5
```

2023-03-10 04:42 UTC, czgdp1807 commented on integration_tests/CMakeLists.txt
> +RUN(NAME loop_05             LABELS cpython llvm)
Works for `c` backend as well?

2023-03-10 06:10 UTC, anutosh491 commented on integration_tests/CMakeLists.txt
> +RUN(NAME loop_05             LABELS cpython llvm)
Yeah should work !

2023-03-10 06:14 UTC, czgdp1807 approved these changes

2023-03-10 06:37 UTC, merged