Dict bool keys
lcompilers/lpython pull request #1771
Opened 2023-05-10 17:25 UTC by kabra1110

Work in progress. Towards #1710.

2023-05-11 05:36 UTC, czgdp1807 commented on src/libasr/codegen/llvm_utils.cpp
> +            }
This logic is correct but the if-else check seems unnecessary. A simple cast from `i1` to `i32` should have done the job. We will see in our tomorrow's meeting how can we do that.

2023-05-13 07:14 UTC, czgdp1807 requested changes
Add tests like looping and writing/reading again and again from a bool dictionary. Value can be of different types like, integer, float, string, etc.

2023-05-13 09:29 UTC, czgdp1807 requested changes

2023-05-13 09:29 UTC, czgdp1807 commented on integration_tests/test_dict_bool.py
We are doing `d[True]` and `d[False]`. Let's **also** do something like,

```
d[i%2 == 0] += 1
```

And check the count of odd and even numbers for some range `[0, n)`. To make sure things work correctly for runtime boolean values.

2023-05-13 09:29 UTC, czgdp1807 commented on tests/reference/asr-test_dict_bool-6f905fd.stdout
Did you generate these by hand?

2023-05-13 09:35 UTC, kabra1110 commented on tests/reference/asr-test_dict_bool-6f905fd.stdout
No, I added (and later removed) a test in `./tests/tests.toml` with `asr` and `asr_json` options.

2023-05-13 09:39 UTC, czgdp1807 commented on tests/reference/asr-test_dict_bool-6f905fd.stdout
Ah I see.Then you can remove these `.stdout` files.

2023-05-13 09:57 UTC, kabra1110 commented on integration_tests/test_dict_bool.py
Looks like `+=` isn't currently supported for `dict` yet. I have added this test with `=`.

2023-05-13 09:58 UTC, czgdp1807 commented on integration_tests/test_dict_bool.py
No worries.

> Looks like `+=` isn't currently supported for `dict` yet.

Let's support this in a separate PR, once you complete this and your other open PR.

2023-05-13 10:01 UTC, czgdp1807 requested changes
If `llvm` test is enabled in `integration_tests/CMakeLists.txt` then most of the time registering the same test in `.toml` file is not needed.

2023-05-13 10:01 UTC, czgdp1807 commented on tests/reference/asr_json-test_dict_bool-8307f87.stdout
Delete this as well.

2023-05-13 10:01 UTC, czgdp1807 commented on tests/reference/asr_json-test_dict_bool-8307f87.json
This one too.

2023-05-13 10:33 UTC, czgdp1807 approved these changes

2023-05-13 10:56 UTC, merged