Add `reserve` for `list`
lcompilers/lpython pull request #2238
Opened 2023-07-31 05:45 UTC by kabra1110

Fixes #2232.

Similar to C++, I have kept this as a function intrinsic to list class.

The test does not work with CPython, as this function is not present there. I'm not entirely sure on how to add a no-op function for this to work.

2023-07-31 10:55 UTC, czgdp1807 requested changes

2023-07-31 10:55 UTC, czgdp1807 commented on integration_tests/test_list_reserve.py
> +    l1.reserve(100)
```suggestion
    reserve(l1, 100)
```

2023-07-31 10:55 UTC, czgdp1807 commented on integration_tests/test_list_reserve.py
> +    l1.reserve(150)
```suggestion
    reserve(l1, 150)
```

2023-07-31 10:55 UTC, czgdp1807 commented on integration_tests/test_list_reserve.py
> +    l2.reserve(100)
```suggestion
    reserve(l2, 100)
```

2023-07-31 10:55 UTC, czgdp1807 commented on integration_tests/test_list_reserve.py
> +    l2.reserve(150)
```suggestion
    reserve(l2, 150)
```

2023-07-31 10:55 UTC, czgdp1807 commented on integration_tests/test_list_reserve.py
> +from lpython import i32, f64
```suggestion
from lpython import i32, f64, reserve
```

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/codegen/llvm_utils.h
> +
This is exactly same as C++.

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +    ListReserve,
```suggestion
    Reserve,
```

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +        INTRINSIC_NAME_CASE(ListReserve)
```suggestion
        INTRINSIC_NAME_CASE(Reserve)
```

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +namespace ListReserve {
```suggestion
namespace Reserve {
```

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +static inline ASR::asr_t* create_ListReserve(Allocator& al, const Location& loc,
```suggestion
static inline ASR::asr_t* create_Reserve(Allocator& al, const Location& loc,
```

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +static inline ASR::expr_t *eval_list_reserve(Allocator &/*al*/,
```suggestion
static inline ASR::expr_t *eval_reserve(Allocator &/*al*/,
```

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +        {static_cast<int64_t>(ASRUtils::IntrinsicFunctions::ListReserve),
```suggestion
        {static_cast<int64_t>(ASRUtils::IntrinsicFunctions::Reserve),
```

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +        {static_cast<int64_t>(ASRUtils::IntrinsicFunctions::ListReserve),
```suggestion
        {static_cast<int64_t>(ASRUtils::IntrinsicFunctions::Reserve),
```

2023-07-31 10:55 UTC, czgdp1807 commented on src/libasr/pass/intrinsic_function_registry.h
> +                {"list.reserve", {&ListReserve::create_ListReserve, &ListReserve::eval_list_reserve}},
```suggestion
                {"list.reserve", {&ListReserve::create_Reserve, &ListReserve::eval_reserve}},
```

2023-07-31 12:15 UTC, certik commented
Beautiful. Yes, as Gagandeep said, you just do:
```
from lpython import reserve
reserve(l, 100)
```
Let's get this in and benchmark again.

2023-08-01 14:14 UTC, certik commented
@czgdp1807 if you could please help, that would be great. Let's get this finished.

2023-08-01 15:12 UTC, czgdp1807 commented
I will meet @kabra1110 today after our meeting ends. We will complete it then.

2023-08-01 17:02 UTC, merged

2023-08-01 17:23 UTC, certik commented
Thanks @czgdp1807 ! 

How do the updated benchmarks look like?