[Parser] Add support for parsing suffixed strings
lcompilers/lpython pull request #624
Opened 2022-06-17 17:33 UTC by akshanshbhatt

2022-06-17 17:44 UTC, Thirumalai-Shaktivel commented
Example Code:
```python
"Hello, {first_name} {last_name}. You are {age}. "
```

2022-06-18 16:16 UTC, certik commented
I think that's a good start. We should add tests.

2022-06-19 05:13 UTC, certik commented
It seems there is some issue on Apple M1:
```console
$ cat a.py
x = 3
a = f"ab{x}cd"
$ lpython --show-ast a.py
(Module [(Assign [(Name x Store)] (ConstantInt 3 ()) ()) (Assign [(Name a Store)] (JoinedStr [(ConstantStr "ab" ()) (FormattedValue (Name x Load) -1 ()) (ConstantStr "cd" ())]) ())] [])
$ lpython --show-ast --new-parser a.py
(Module [(Assign [(Name x Store)] (ConstantInt 3 ()) ()) (Assign [(Name a Store)] (JoinedStr [(ConstantStr "????Eb" ()) (FormattedValue (Name x Load) -1 ()) (ConstantStr "cd" ())]) ())] [])
```

2022-06-19 05:19 UTC, certik requested changes
The suggestions above fix the dangling pointers issue.

2022-06-19 05:19 UTC, certik commented on src/lpython/parser/semantics.h
> +    Vec<ast_t *> exprs;
```suggestion
    Vec<expr_t *> exprs;
```

2022-06-19 05:19 UTC, certik commented on src/lpython/parser/semantics.h
> +    return make_JoinedStr_t(al, l, EXPRS(exprs), exprs.size());
```suggestion
    return make_JoinedStr_t(al, l, exprs.p, exprs.size());
```

2022-06-19 05:19 UTC, certik commented on src/lpython/parser/semantics.h
> +                exprs.push_back(al, tmp);
```suggestion
                exprs.push_back(al, ASR::down_cast<ASR::expr_t>(tmp));
```

2022-06-19 05:19 UTC, certik commented on src/lpython/parser/semantics.h
> +                tmp = make_ConstantStr_t(al, l, (char *)strs[i].c_str(), nullptr);
You can't do this, as it becomes dangling when `strs` goes out of scope. You have to allocate all strings using our allocator, such as:
```suggestion
                tmp = make_ConstantStr_t(al, l, s2c(al, strs[i]), nullptr);
```

2022-06-19 05:19 UTC, certik commented on src/lpython/parser/semantics.h
> +                        (char *)strs[i].c_str(), expr_contextType::Load);
```suggestion
                        s2c(al, strs[i]), expr_contextType::Load);
```

2022-06-19 12:52 UTC, Thirumalai-Shaktivel commented on src/lpython/parser/semantics.h
> +
```suggestion
```

2022-06-19 18:36 UTC, certik commented
@akshanshbhatt does this work now on M1, or is there still an issue?

2022-06-19 18:51 UTC, akshanshbhatt commented
> @akshanshbhatt does this work now on M1, or is there still an issue?

Yeah, the issue is resolved now. Works perfectly fine!

2022-06-19 19:36 UTC, certik approved these changes
Looks great to me, thanks!

@Thirumalai-Shaktivel if you are ok with the PR, you can go ahead and merge it.

2022-06-20 06:05 UTC, akshanshbhatt commented
@certik, I just noticed that the expression tree is not generated correctly in the AST. Is there any way we can handle this?

```zsh
❯ cat examples/expr2.py
f'''
a is {a}
b is {b}
sum is {a + b}
'''
❯ lpyast examples/expr2.py
(Module [(Expr (JoinedStr [(ConstantStr "
a is " ()) (FormattedValue (Name a Load) -1 ()) (ConstantStr "
b is " ()) (FormattedValue (Name b Load) -1 ()) (ConstantStr "
sum is " ()) (FormattedValue (BinOp (Name a Load) Add (Name b Load)) -1 ()) (ConstantStr "
" ())]))] [])
❯ lpynewpar examples/expr2.py
(Module [(Expr (JoinedStr [(ConstantStr "
a is " ()) (FormattedValue (Name a Load) -1 ()) (ConstantStr "
b is " ()) (FormattedValue (Name b Load) -1 ()) (ConstantStr "
sum is " ()) (FormattedValue (Name a + b Load) -1 ()) (ConstantStr "
" ())]))] [])
```

2022-06-20 06:08 UTC, certik commented
It seems you just have to convert `a+b` into `(BinOp (Name a Load) Add (Name b Load))`, so probably just call `visit_expr()` on it.

2022-06-20 06:10 UTC, certik commented
This might be complicated, as we have to run the full parser on it. I recommend for now to ignore this bug, let's get this merged, and we can resolve this later.

2022-06-20 06:11 UTC, akshanshbhatt commented
Should I open an issue regarding this?

2022-06-20 06:12 UTC, certik commented
Yes, go ahead and open up an issue for this. 

Thirumalai might be busy, but this is ready to be merged as far as I am concerned.

2022-06-20 06:14 UTC, akshanshbhatt commented
> Thirumalai might be busy, but this is ready to be merged as far as I am concerned. @akshanshbhatt are you ok if I merge it?

Yeah, sure!

2022-06-20 06:31 UTC, merged

2022-06-20 06:32 UTC, certik commented
Thanks!

2022-06-20 09:56 UTC, Thirumalai-Shaktivel commented
Thank you @certik for reviewing and merging this PR.
Also, Thank you @akshanshbhatt for making the changes as suggested and adding the tests.