Make `len()` work with lists
lcompilers/lpython pull request #930
Opened 2022-08-06 11:01 UTC by namannimmo10

Fixes #925

2022-08-06 11:02 UTC, namannimmo10 commented
I am also going to do this for tuples.

2022-08-06 11:07 UTC, Thirumalai-Shaktivel commented
Perfect, I was also planning to do the same.

2022-08-06 11:08 UTC, Thirumalai-Shaktivel commented on integration_tests/test_builtin_len.py
> +
Can you please add this test as well?
```py
    list_len: i32 = len([1.0, 2.0])
    assert list_len == 2
```

2022-08-06 11:35 UTC, Thirumalai-Shaktivel commented on src/libasr/codegen/asr_to_llvm.cpp
> +        tmp = list_api->len(plist);
`list_len: i32 = len([1.0, 2.0])` for this example, why not use the value from `x.m_value`??
```suggestion
        if (x.m_value) {
            this->visit_expr(*x.m_value);
        } else {
            uint64_t ptr_loads_copy = ptr_loads;
            ptr_loads = 0;
            this->visit_expr(*x.m_arg);
            ptr_loads = ptr_loads_copy;
            llvm::Value* plist = tmp;
            tmp = list_api->len(plist);
        }
```

2022-08-06 15:06 UTC, czgdp1807 requested changes

2022-08-06 15:06 UTC, czgdp1807 commented on src/libasr/codegen/llvm_utils.cpp
> +        return LLVM::CreateLoad(*builder, get_pointer_to_current_capacity(list));
```suggestion
        return LLVM::CreateLoad(*builder, get_pointer_to_current_end_point(list));
```

2022-08-06 15:08 UTC, czgdp1807 requested changes

2022-08-06 15:08 UTC, czgdp1807 commented on integration_tests/test_builtin_len.py
> +    l3.append(3)
Let's do 20-30 appends in a loop and then check if the `len(xyz_list)` gives correct output.

2022-08-07 06:33 UTC, Thirumalai-Shaktivel approved these changes
LGTM! Thank you

2022-08-07 07:21 UTC, namannimmo10 commented
@czgdp1807 - is this ready?

2022-08-07 07:23 UTC, czgdp1807 approved these changes

2022-08-07 07:24 UTC, merged