Gmean, Hmean expanded for other datatypes
lcompilers/lpython pull request #956
Opened 2022-08-12 07:43 UTC by Madhav2310

2022-08-12 08:41 UTC, Smit-create commented on src/runtime/statistics.py
> +def harmonic_mean(x: list[i64]) -> f64:
```suggestion
    return float(k/sum)
 
@overload
def harmonic_mean(x: list[i64]) -> f64:
```

2022-08-12 08:41 UTC, Smit-create commented on src/runtime/statistics.py
> +@overload
```suggestion
    return product**(1/k)

@overload
```

2022-08-12 09:36 UTC, czgdp1807 requested changes

2022-08-12 09:36 UTC, czgdp1807 commented on src/runtime/statistics.py
> +        if(x[i]<=0):
```suggestion
        if x[i] <= 0:
```

2022-08-12 09:36 UTC, czgdp1807 commented on src/runtime/statistics.py
> +        if(x[i]<=0):
```suggestion
        if x[i] <= 0:
```

2022-08-12 09:36 UTC, czgdp1807 commented on src/runtime/statistics.py
> +        if(x[i]<=0.0):
```suggestion
        if x[i] <= 0.0:
```

2022-08-12 09:36 UTC, czgdp1807 commented on src/runtime/statistics.py
> +        if(x[i]<0.0):
```suggestion
        if x[i] < 0.0:
```

2022-08-12 09:36 UTC, czgdp1807 commented on src/runtime/statistics.py
> +        if(x[i]<0):
```suggestion
        if x[i] < 0:
```

2022-08-12 09:36 UTC, czgdp1807 commented on src/runtime/statistics.py
> +        if(x[i]<0.0):
```suggestion
        if x[i] < 0.0:
```

2022-08-12 09:54 UTC, namannimmo10 commented
@Madhav2310 -- please read [PEP 8](https://peps.python.org/pep-0008/).

2022-08-13 15:00 UTC, czgdp1807 requested changes

2022-08-13 15:00 UTC, czgdp1807 commented on integration_tests/test_statistics.py
> +    d = [9,0,46]
```suggestion
    d = [9, 0, 46]
```

2022-08-13 15:01 UTC, czgdp1807 approved these changes

2022-08-14 08:23 UTC, merged

2022-08-14 08:48 UTC, czgdp1807 commented
I removed `coviariance` and `correlation` for now from this PR. You can add it in a new PR. Thanks for contributing.